twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        img_default: '/images/products/no-image.jpg'

when@test:
    twig:
        strict_variables: true
